class users {
    id : integer
    --
    name : string
    email : string
    password : string
    roles : string
    address : text
    houseNumber : string
    phoneNumber : string
    city : string
}

class food {
    id : integer
    --
    name : string
    description : text
    ingredients : text
    price : integer
    rate : double
    types : string
    photo : text
}

class transactions {
    id : integer
    --
    user_id : integer
    food_id : integer
    quantity : integer
    total : integer
    status : string
    payment_url : text
}

users ||--|{ transactions
food ||--|{ transactions